Make ANSSI targets a subcrate of `crypto_base`
Cosmian/crypto_base pull request #30
Opened 2022-07-18 15:20 UTC by tbrezot

Move into a `anssi` subcrate:
- the asymmetric public and private keys;
- the symmetric encryption along with the DEM trait and implementation based on AES, the block and metadata structures and logic;
- the error type;
- the KDF implementation based on hkdf;
- the `CsRng` structure

2022-08-23 06:29 UTC, Manuthor commented on src/lib.rs
> +pub enum CryptoBaseError {
use a dedicated file?

2022-08-23 06:29 UTC, Manuthor commented on Cargo.toml
> +cosmian_crypto_core = { git = "https://github.com/Cosmian/crypto_core.git", branch = "features/use_generic_arrays" }
to be changed once `crypto_core` generic-array feature is merged

2022-08-23 14:25 UTC, ThibsG approved these changes

2022-08-23 14:27 UTC, merged

2022-09-17 19:22 UTC, Maario86 requested changes
[]()